# Dockerfile.dev

FROM node:22 AS base
WORKDIR /usr/src/app
COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/
RUN npm install
COPY shared/ ./shared/

FROM base AS server-dev
COPY server/ ./server/
WORKDIR /usr/src/app/server
EXPOSE 3001
CMD ["npm", "run", "dev"]

FROM base AS client-dev
COPY client/ ./client/
WORKDIR /usr/src/app/client
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]