services:
  mongodb:
    image: mongo:8
    container_name: viulumeri-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: viulumeri
    volumes:
      - mongodb_data:/data/db
    networks:
      - viulumeri-network

volumes:
  mongodb_data:

networks:
  viulumeri-network:
    driver: bridge

