apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viulumeri-audio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
