apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viulumeri-staging

images:
- name: jayzstep/viulumeri
  newName: jayzstep/viulumeri
  newTag: 74e0de149cd1d6302dac5ae4d7f7b9a1d4cbb39c

resources:
- namespace.yaml
- ../base
- ingress.yaml

patches:
- path: viulumeri-configmap-patch.yaml
