apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viulumeri-staging

images:
- name: jayzstep/viulumeri
  newName: jayzstep/viulumeri
  newTag: f4e0bcb8b78db9fac55453bceb4fe57ad52cbabe

resources:
- namespace.yaml
- ../base
- ingress.yaml

patches:
- path: viulumeri-configmap-patch.yaml
