apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viulumeri-staging

images:
- name: jayzstep/viulumeri
  newName: jayzstep/viulumeri
  newTag: 13c34399ca95c16f0c8c1c5acb8233ee4689e773

resources:
- namespace.yaml
- ../base
- ingress.yaml

patches:
- path: viulumeri-configmap-patch.yaml
