apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viulumeri-staging

images:
- name: jayzstep/viulumeri
  newName: jayzstep/viulumeri
  newTag: e2d4d67f54d2702a9ad60904abc82b81913879a7

resources:
- namespace.yaml
- ../base
- ingress.yaml

patches:
- path: viulumeri-configmap-patch.yaml
