apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viulumeri-staging

images:
- name: jayzstep/viulumeri
  newName: jayzstep/viulumeri
  newTag: de34123fc2a181fefc6219e9674a372c9379f8ec

resources:
- namespace.yaml
- ../base
- ingress.yaml

patches:
- path: viulumeri-configmap-patch.yaml
